Repository githubschool/floss-workshop, pull requests merged in 2020-11, with the labels that each got.

#13 Update caption to be more descriptive
  _slides/03-ericalloyd.md
Labels: caption-updates

#11 Anhtqweb caption
  _slides/08-anhtqweb.md
Labels: caption-update

#10 Update caption of Slide 16.
  _slides/16-mjbanvard.md
Labels: caption-update

#15 Updated caption of slides of lingineni555
  _slides/14-lingineni555.md
Labels: caption-update

#9 Updated caption
  _slides/04-21shield.md
Labels: new-caption

#8 Update allthedoll's caption to match her Octocat
  _slides/02-allthedoll.md
Labels: enhancement

#25 Update Caption, here's my commit!
  _slides/20-muraterzioglu.md
Labels: caption-update
